name: Run the bots
on:
  schedule:
    - cron: '39-44 23,2,5,8,11,14,17,20 * * *'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  run-bots:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: Install uv
        run: bash -c "$(curl -Lf https://astral.sh/uv/install.sh)"

      - name: Run the bots
        run: |
          uv run ./master.py &
          for i in {0..30}; do
            [[ -s ./master_data ]] && break
            sleep 1
          done
          uv run ./slave.py
        env:
          MASTER_TOKEN: ${{ secrets.MASTER_TOKEN }}
          SLAVE_TOKEN: ${{ secrets.SLAVE_TOKEN }}
          BOT_SYNC_ENABLED: 0
