name: Run the bots
on:
  schedule:
    - cron: '43 1 * * *'
    - cron: '11 5 * * *'
    - cron: '27 9 * * *'
    - cron: '07 13 * * *'
    - cron: '37 17 * * *'
    - cron: '19 22 * * *'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  run-bots:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: Install uv
        run: bash -c "$(curl -Lf https://astral.sh/uv/install.sh)"

      - name: Run the bots
        run: |
          uv run ./master.py &
          uv run ./slave.py
        env:
          MASTER_TOKEN: ${{ secrets.MASTER_TOKEN }}
          SLAVE_TOKEN: ${{ secrets.SLAVE_TOKEN }}
          MASTER_ID: ${{ vars.MASTER_ID }}
          BOT_SYNC_ENABLED: 0
